import React from "react";
import Head from "next/head";
import BookDemobanner from "@/components/BookDemo/BookDemoBanner";
import BookDemoForm from "@/components/BookDemo/BookDemoForm";
import CTASection from "@/components/BookDemo/CTASection";
const bookdemo = () => {
  return (
    <>
      <Head>
        <title>ADDVantage Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        {/* banner section  */}
        <BookDemobanner />
        {/* banner section  */}
        {/* book demo form section */}
        <BookDemoForm />
        {/* book demo form section */}
        {/* CTA section */}
        <CTASection />
        {/* CTA section */}
      </div>
    </>
  );
};

export default bookdemo;
