import Conactusabanner from "@/components/Contact/Conactusabanner";
import ContactForm from "@/components/Contact/ContactForm";
import Head from "next/head";
const contactus = () => {
  return (
    <div>
      <Head>
        <title>ADDVantage Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="contactuspagemain">
        <Conactusabanner />
        <ContactForm />
      </div>
    </div>
  );
};

export default contactus;
