import Head from "next/head";
import HomeBanner from "@/components/Home/HomeBanner";
import HomeContact from "@/components/Home/HomeContact";
import AlldayDrProduct from "@/components/Home/HomeProducts/AlldayDrProduct";
import ApplocumProduct from "@/components/Home/HomeProducts/ApplocumProduct";
import HealthyaProduct from "@/components/Home/HomeProducts/HealthyaProduct";
import HealthyaStations from "@/components/Home/HomeProducts/HealthyaStations";
import PharmsmartProduct from "@/components/Home/HomeProducts/PharmsmartProduct";
import ADDvtangeMindsProduct from "@/components/Home/HomeProducts/ADDvtangeMindsProduct";
import Homeservices from "@/components/Home/Homeservices";
import HomeAccreditations from "@/components/Home/HomeAccreditations";
import { Element } from "react-scroll";
import React, { useEffect, useRef, useState } from "react";

export default function Home() {
  const brandaddvtageRef = useRef(null);
  const brandaddvmindsRef = useRef(null);
  const brandAlldayDrRef = useRef(null);
  const brandHealthyaRef = useRef(null);
  const brandAppLocumRef = useRef(null);
  const brandPharmsmartRef = useRef(null);
  const brandConatctformRef = useRef(null);
  const [section, setSection] = useState({
    brandaddvtageRef,
    brandaddvmindsRef,
    brandAlldayDrRef,
    brandHealthyaRef,
    brandAppLocumRef,
    brandPharmsmartRef,
    brandConatctformRef,
  });
  useEffect(() => {
    // console.log(window.location);
    let sectionId = localStorage.getItem("sectionRef");
    if (sectionId) {
      console.log(sectionId);
      setTimeout(() => {
        const y = section[sectionId].current.childBindings.domNode.offsetTop;
        window.scroll({
          top: y,
          behavior: "smooth",
        });
        localStorage.removeItem("sectionRef");
      }, 400);
    }
  }, [section]);

  return (
    <>
      <Head>
        <title>ADDVantage Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="mainbody">
        <Element
          id="ADDVantage-brands"
          className="hero-section"
          name="ADDVantage-brands"
          ref={brandaddvtageRef}
        >
          <HomeBanner />
        </Element>
        {/* SERVICES-9*/}
        <Element
          id="services-9"
          className="services-9 pt-80 pb-70 services-section division"
          name="services-9"
        >
          <Homeservices />
          {/* END SERVICES-9 WRAPPER */}
        </Element>
        {/*End container*/}

        {/* END SERVICES-9 */}

        {/* HomeProducts section start */}
        <Element
          name="brand-alldayDr"
          className="brand-alldayDr bg-lightgrey pt-100 pb-100 content-section division"
          id="brand-alldayDr"
          ref={brandAlldayDrRef}
        >
          {/* <HomeProducts /> */}
          <AlldayDrProduct />
        </Element>
        <Element
          name="brand-healthya"
          className="brand-healthya bg-03 pt-100 pb-100 content-section division"
          id="brand-healthya"
          ref={brandHealthyaRef}
        >
          <HealthyaProduct />
        </Element>
        <Element
          id="brand-AppLocum"
          className="brand-AppLocum pt-100 pb-30 content-section division"
          name="brand-AppLocum"
          ref={brandAppLocumRef}
        >
          <ApplocumProduct />
        </Element>
        <Element
          id="brand-Coach2health"
          className="brand-healthya bg-03 pt-100 content-section division"
        >
          <HealthyaStations />
        </Element>
        <Element
          id="brand-addminds"
          className="brand-AppLocum pt-100 pb-100 content-section division"
          name="brand-addminds"
          ref={brandaddvmindsRef}
        >
          <ADDvtangeMindsProduct />
        </Element>
        <Element
          id="brand-Pharmsmart"
          className="brand-healthya bg-03 pt-100 pb-30 content-section division"
          name="brand-Pharmsmart"
          ref={brandPharmsmartRef}
        >
          <PharmsmartProduct />
        </Element>
        {/* HomeProducts section end */}
        {/* Home Accreditations section start */}
        <HomeAccreditations />
        {/* Home Accreditations section end */}
        {/* Home Contact section start */}
        <Element
          id="contacts-4"
          className="contacts-4 bg-01 wide-60 contacts-section division"
          name="contacts-4"
          ref={brandConatctformRef}
        >
          <HomeContact />
        </Element>

        {/* Home Contact section end */}
      </main>
    </>
  );
}
