import MeetTeamBanner from "@/components/MeettheTeam/MeetTeamBanner";
import Head from "next/head";
import TeamMembers from "@/components/MeettheTeam/TeamMembers";
import Meettheform from "@/components/MeettheTeam/Meettheform";
import React, { useRef } from "react";
import { Element } from "react-scroll";

const meettheteam = () => {
  return (
    <div>
      <Head>
        <title>ADDVantage Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* banner section */}
      <MeetTeamBanner />
      {/* banner section */}
      {/* teams section */}
      <TeamMembers />
      {/* teams section */}
      {/* team form section */}
      <Element
        id="contacts-4"
        className="contacts-4 bg-01 wide-60 contacts-section division"
        name="contacts-4"
      >
        <Meettheform />
        {/* team form section */}
      </Element>
    </div>
  );
};

export default meettheteam;
